apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-platform

resources:
  - ../../base
  - ../../clickstream-service

# Override images to use GHCR
images:
  - name: localhost:5001/custom-flink
    newName: ghcr.io/borisbesky/custom-flink
    newTag: latest
  - name: localhost:5001/custom-spark
    newName: ghcr.io/borisbesky/custom-spark
    newTag: latest
  - name: ghcr.io/your-org/clickstream-backend
    newName: ghcr.io/borisbesky/clickstream-backend
    newTag: latest
  - name: ghcr.io/your-org/clickstream-frontend
    newName: ghcr.io/borisbesky/clickstream-frontend
    newTag: latest
